[package]
name = "primithium/attune"
description = "a tiny utility module for pitching sounds with 12-TET\n\nhttps://primithium.github.io/Attune/"
version = "0.1.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Primithium <primithium@gmail.com>"]

[dependencies]
